### PR TITLE
Scope variable name reused in nested loop

### PR DESCRIPTION
**Pull request by kapsalis**
Fix the bug in which the scope variable name is reused in a nested loop

### CODE REVIEW

**Comment by kairoaraujo** [comment]
Thank you, @kapsalis, for the contribution to RSTUF 🎉

**Comment by kairoaraujo** [comment]
@kapsalis, Could you [sign off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) the commits (basically using the `-s`)?
It is essential to agree with the [project's DCO](https://repository-service-tuf.readthedocs.io/en/latest/devel/contributing.html#dco)

**Comment by kapsalis** [comment]
> @kapsalis, Could you [sign off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) the commits (basically using the `-s`)? It is essential to agree with the [project's DCO](https://repository-service-tuf.readthedocs.io/en/latest/devel/contributing.html#dco)

Hi @kairoaraujo . I signed off the commits and pushed again! Thank you for the note

**Review by kairoaraujo — APPROVED** [review]

**Review by MVrachev — APPROVED** [review]
It's awesome to see new contributors!
LGTM!

**Pull request merged**
