### PR TITLE
Fix: issue #233

### PR DESCRIPTION
**Pull request by JanKaczmarski**
Changed ports so no error occurs.

### CODE REVIEW

**Comment by kairoaraujo** [comment]
Hi @JanKaczmarski, thank you for your contribution to opening this PR.

I think the best approach for this will be updating the documentation `README.rst` instead of the `docker-compose.yml`.

**Comment by JanKaczmarski** [comment]
Hi @kairoaraujo , thanks for pointing out the problem in my approach. 

I'll try to fix it.

**Comment by MVrachev** [comment]
Could you also add sign-off to your commit @JanKaczmarski?
This way if in the future someone wants to ask you about your change your email will be there.
Thanks for contributing!

**Comment by JanKaczmarski** [comment]
Okay @MVrachev

**Pull request closed without merging**
