### PR TITLE
docs/tests: add missing delegation path in payload

### PR DESCRIPTION
**Pull request by MVrachev**
In the example payload.json we use for our swagger.json we define the metadata structure.
There we define that "2.targets.json" delegates all target files within the following paths "*/*" and "*/*/*/*".
I noticed we are missing the case where there is a target file in the root directory or in "*".
That's a case we want to test in our functional tests in the umbrella repository and it makes sense to support such targets.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

### CODE REVIEW

**Review by kairoaraujo — APPROVED** [review]

**Review by kairoaraujo — COMMENTED** [review]
It needs make-docs to have the new doc built.

**Comment by MVrachev** [comment]
It's ready now @kairoaraujo.

**Comment by MVrachev** [comment]
Wait, @kairoaraujo.
We need to resign the metadata if we change the delegation attributes...

**Review by kairoaraujo — APPROVED** [review]

**Comment by MVrachev** [comment]
I updated the example payload.json with the one you can get from running:
```
pytest -vv rstuf-cli/tests/unit/cli/admin/test_ceremony.py::TestCeremonyGroupCLI::test_ceremony_start_default_values
```
That way the `2.targets.json` is resigned, but this means that all keys had to be updated as well.

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
